#!/usr/bin/env python3
# Generated by OpenCode on 2026-04-28
"""Quality checker for knowledge entry JSON files.

Evaluates knowledge entries across 5 dimensions and assigns a grade.
"""

import json
import sys
from dataclasses import dataclass, field
from pathlib import Path


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
SUMMARY_MAX_SCORE = 25
TECH_DEPTH_MAX_SCORE = 25
FORMAT_MAX_SCORE = 20
TAGS_MAX_SCORE = 15
BUZZ_MAX_SCORE = 15

GRADE_A_THRESHOLD = 80
GRADE_B_THRESHOLD = 60

PROGRESS_WIDTH = 20

CHINESE_BUZZWORDS = [
    "赋能",
    "抓手",
    "闭环",
    "打通",
    "全链路",
    "底层逻辑",
    "颗粒度",
    "对齐",
    "拉通",
    "沉淀",
    "强大的",
]

ENGLISH_BUZZWORDS = [
    "groundbreaking",
    "revolutionary",
    "game-changing",
    "cutting-edge",
]

TECH_KEYWORDS = [
    "transformer",
    "llm",
    "agent",
    "rag",
    "fine-tuning",
    "prompt",
    "embedding",
    "vector",
    "diffusion",
    "gan",
    "cnn",
    "rnn",
    "bert",
    "gpt",
    "reinforcement",
    "supervised",
    "unsupervised",
    "clustering",
    "classification",
    "regression",
    "神经网络",
    "深度学习",
    "机器学习",
    "强化学习",
    "自然语言处理",
    "计算机视觉",
    "大模型",
    "预训练",
    "微调",
    "推理",
    "部署",
    "量化",
    "蒸馏",
    "算法",
    "模型",
    "框架",
    "api",
    "sdk",
]

STANDARD_TAGS = {
    "large-language-model",
    "llm",
    "agent",
    "multi-agent",
    "rag",
    "prompt-engineering",
    "fine-tuning",
    "machine-learning",
    "deep-learning",
    "nlp",
    "computer-vision",
    "multi-modal",
    "reinforcement-learning",
    "open-source",
    "github",
    "paper",
    "framework",
    "tool",
    "benchmark",
    "evaluation",
    "inference",
    "deployment",
    "quantization",
    "distillation",
    "transformer",
    "gnn",
    "diffusion",
    "cv",
    "text-generation",
    "code-generation",
    "embedding",
    "vector-database",
    "knowledge-graph",
    "safety",
    "alignment",
}

TIMESTAMP_FIELDS = [
    "collected_at",
    "analyzed_at",
    "published_at",
    "created_at",
    "timestamp",
]


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------
@dataclass
class DimensionScore:
    name: str
    score: int
    max_score: int
    details: str = ""


@dataclass
class QualityReport:
    file_path: Path
    total_score: int
    grade: str
    dimensions: list[DimensionScore] = field(default_factory=list)
    max_total: int = 100
    passed: bool = True

    def __post_init__(self) -> None:
        self.passed = self.grade != "C"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def load_json(path: Path) -> dict | None:
    """Load and parse a JSON file. Returns None on failure."""
    try:
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, dict) else None
    except Exception:
        return None


def progress_bar(score: int, max_score: int, width: int = PROGRESS_WIDTH) -> str:
    """Return a Unicode progress bar string."""
    if max_score <= 0:
        filled = 0
    else:
        filled = int((score / max_score) * width)
    filled = max(0, min(width, filled))
    bar = "█" * filled + "░" * (width - filled)
    return f"[{bar}] {score}/{max_score}"


def calculate_grade(total: int) -> str:
    """Return grade letter based on total score."""
    if total >= GRADE_A_THRESHOLD:
        return "A"
    if total >= GRADE_B_THRESHOLD:
        return "B"
    return "C"


def collect_paths(args: list[str]) -> list[Path]:
    """Expand CLI arguments into a flat list of Path objects."""
    paths: list[Path] = []
    for arg in args:
        p = Path(arg)
        if "*" in arg or "?" in arg:
            if p.parent.exists():
                paths.extend(sorted(p.parent.glob(p.name)))
        elif p.is_dir():
            paths.extend(sorted(p.glob("*.json")))
        else:
            paths.append(p)
    # Deduplicate while preserving order
    seen: set[Path] = set()
    unique_paths: list[Path] = []
    for path in paths:
        rp = path.resolve()
        if rp not in seen:
            seen.add(rp)
            unique_paths.append(path)
    return unique_paths


# ---------------------------------------------------------------------------
# Evaluators
# ---------------------------------------------------------------------------
def evaluate_summary(data: dict) -> DimensionScore:
    """Evaluate summary quality."""
    summary = data.get("summary", "")
    if not isinstance(summary, str):
        return DimensionScore("摘要质量", 0, SUMMARY_MAX_SCORE, "summary 非字符串")

    length = len(summary)
    details_parts: list[str] = []

    # Base score by length
    if length >= 50:
        base_score = 20
        details_parts.append(f"长度 {length}，达标")
    elif length >= 20:
        base_score = 10
        details_parts.append(f"长度 {length}，基本达标")
    else:
        base_score = max(0, int(length / 20 * 10))
        details_parts.append(f"长度 {length}，未达标")

    # Keyword bonus
    text_lower = summary.lower()
    matched = [kw for kw in TECH_KEYWORDS if kw.lower() in text_lower]
    bonus = min(5, len(matched) * 2) if matched else 0
    if bonus:
        details_parts.append(f"含技术关键词 +{bonus}")

    score = min(SUMMARY_MAX_SCORE, base_score + bonus)
    return DimensionScore("摘要质量", score, SUMMARY_MAX_SCORE, "; ".join(details_parts))


def evaluate_tech_depth(data: dict) -> DimensionScore:
    """Evaluate technical depth based on score field."""
    raw = data.get("score")
    if isinstance(raw, (int, float)):
        score = round(float(raw) * 2.5)
        details = f"score={raw} → {score}/{TECH_DEPTH_MAX_SCORE}"
    else:
        score = 0
        details = "缺少有效 score 字段，计 0 分"
    return DimensionScore("技术深度", score, TECH_DEPTH_MAX_SCORE, details)


def evaluate_format(data: dict) -> DimensionScore:
    """Evaluate format compliance."""
    checks = {
        "id": bool(data.get("id")),
        "title": bool(data.get("title")),
        "source_url": bool(data.get("source_url")),
        "status": bool(data.get("status")),
        "时间戳": any(bool(data.get(f)) for f in TIMESTAMP_FIELDS),
    }
    score = sum(4 for ok in checks.values() if ok)
    missing = [k for k, ok in checks.items() if not ok]
    details = f"缺失: {', '.join(missing)}" if missing else "格式完整"
    return DimensionScore("格式规范", score, FORMAT_MAX_SCORE, details)


def evaluate_tags(data: dict) -> DimensionScore:
    """Evaluate tag precision."""
    tags = data.get("tags", [])
    if not isinstance(tags, list):
        return DimensionScore("标签精度", 0, TAGS_MAX_SCORE, "tags 类型错误")

    count = len(tags)
    if count == 0:
        return DimensionScore("标签精度", 0, TAGS_MAX_SCORE, "无标签")

    # Quantity score
    if 1 <= count <= 3:
        qty_score = 5
        qty_detail = "数量适中"
    else:
        qty_score = 0
        qty_detail = f"数量 {count}，建议 1-3 个"

    # Quality score based on standard tags
    matched = sum(1 for t in tags if str(t).lower() in STANDARD_TAGS)
    quality_score = min(10, round(matched * 3.33))

    score = min(TAGS_MAX_SCORE, qty_score + quality_score)
    details = f"{qty_detail}; 标准标签 {matched}/{count}"
    return DimensionScore("标签精度", score, TAGS_MAX_SCORE, details)


def evaluate_buzzwords(data: dict) -> DimensionScore:
    """Evaluate buzzword usage."""
    text_parts = [str(data.get("title", "")), str(data.get("summary", ""))]
    text = " ".join(text_parts)

    found_cn = [w for w in CHINESE_BUZZWORDS if w in text]
    text_lower = text.lower()
    found_en = [w for w in ENGLISH_BUZZWORDS if w.lower() in text_lower]

    found = found_cn + found_en
    deduction = len(found) * 3
    score = max(0, BUZZ_MAX_SCORE - deduction)

    if found:
        shown = ", ".join(found[:5])
        ellipsis = "..." if len(found) > 5 else ""
        details = f"发现空洞词: {shown}{ellipsis} (-{deduction})"
    else:
        details = "未检测到空洞词"
    return DimensionScore("空洞词检测", score, BUZZ_MAX_SCORE, details)


def evaluate_file(path: Path) -> QualityReport:
    """Run all evaluators on a single file."""
    data = load_json(path)
    if data is None:
        dims = [
            DimensionScore("摘要质量", 0, SUMMARY_MAX_SCORE, "JSON 解析失败"),
            DimensionScore("技术深度", 0, TECH_DEPTH_MAX_SCORE, "JSON 解析失败"),
            DimensionScore("格式规范", 0, FORMAT_MAX_SCORE, "JSON 解析失败"),
            DimensionScore("标签精度", 0, TAGS_MAX_SCORE, "JSON 解析失败"),
            DimensionScore("空洞词检测", 0, BUZZ_MAX_SCORE, "JSON 解析失败"),
        ]
        return QualityReport(path, 0, "C", dims, passed=False)

    dims = [
        evaluate_summary(data),
        evaluate_tech_depth(data),
        evaluate_format(data),
        evaluate_tags(data),
        evaluate_buzzwords(data),
    ]
    total = sum(d.score for d in dims)
    grade = calculate_grade(total)
    return QualityReport(path, total, grade, dims)


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------
def print_report(report: QualityReport) -> None:
    """Print a quality report to stdout."""
    print(f"\n{report.file_path}")
    for dim in report.dimensions:
        label = f"{dim.name:<8}"
        print(f"  {label} {progress_bar(dim.score, dim.max_score)}  {dim.details}")
    print(f"  {'总分':<8} {progress_bar(report.total_score, report.max_total)}  等级: {report.grade}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main(argv: list[str] | None = None) -> int:
    """Entry point. Returns 0 if no C grades, 1 otherwise."""
    if argv is None:
        argv = sys.argv[1:]

    if not argv:
        print("Usage: python hooks/check_quality.py <json_file> [json_file2 ...]")
        return 1

    paths = collect_paths(argv)
    if not paths:
        print("No JSON files found matching the provided arguments.")
        return 1

    reports: list[QualityReport] = []
    for path in paths:
        report = evaluate_file(path)
        reports.append(report)
        print_report(report)

    total_files = len(reports)
    passed = sum(1 for r in reports if r.passed)
    failed = total_files - passed

    print("\n" + "=" * 60)
    print(f"Total files : {total_files}")
    print(f"Passed (A/B): {passed}")
    print(f"Failed (C)  : {failed}")
    print("=" * 60)

    return 1 if failed > 0 else 0


if __name__ == "__main__":
    sys.exit(main())
